version: "3"
services:
  app:
    build: .
    networks:
      - mynetwork
    links:
      - db
    ports:
      - "8008:8008"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql
    networks:
      - mynetwork
    ports:
      - "32000:3306"
    environment:
      - MYSQL_DATABASE=flaskapp
      - MYSQL_ROOT_PASSWORD=Atakan2002
    volumes:
      - ./data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
