version: "2"
services:
  app:
    build: ./app
    networks:
      - mynetwork
    links:
      - db
    ports:
      - "8008:8008"
    depends_on:
      - db


  db:
    image: mysql
    networks:
      - mynetwork
    ports:
      - "32000:3306"
    environment:
      - MYSQL_DATABASE=flaskapp
      - MYSQL_ROOT_PASSWORD=Atakan2002
    volumes:
      - ./data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
  
networks:
  mynetwork:
    driver: bridge